"""

Revision ID: f2ee2fc0ff90
Revises: 55b3f6f59e23
Create Date: 2023-02-28 15:01:19.950401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2ee2fc0ff90'
down_revision = '55b3f6f59e23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('chat_user', sa.Integer(), nullable=True))
    op.create_foreign_key(
        op.f('fk_chat_chat_user_user'),
        'chat',
        'user',
        ['chat_user'],
        ['id'],
        ondelete='CASCADE',
    )
    op.add_column('user', sa.Column('user_chat_fk', sa.Integer(), nullable=False))
    op.create_foreign_key(
        op.f('fk_user_user_chat_fk_chat'), 'user', 'chat', ['user_chat_fk'], ['id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_user_chat_fk_chat'), 'user', type_='foreignkey')
    op.drop_column('user', 'user_chat_fk')
    op.drop_constraint(op.f('fk_chat_chat_user_user'), 'chat', type_='foreignkey')
    op.drop_column('chat', 'chat_user')
    # ### end Alembic commands ###
